#!/bin/bash
################################################################################
# 
# Copyright (c) 2019 NUAA AeroLab
# 
# @author   Jiang Yang (pokerpoke@qq.com)
# @date     2018-08
# @brief    
# @version  0.0.1
# 
# Modified By:    Jiang Yang (pokerpoke@qq.com)
#
# Last Modified:  2023-11-08
# Modified By:    HangX-Ma (contour.9x@gmail.com)
# 
################################################################################
set -e

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
CMAKE_SOURCE_DIR=$(pwd)
cd ${CMAKE_SOURCE_DIR}

cmake -B build
cmake --build build -j`nproc`

file_path=$1
./build/${file_path%%\.cc}