#!/bin/bash
################################################################################
# 
# Copyright (c) 2018 南京航空航天大学 航空通信网络研究室
# 
# @author   姜阳 (j824544269@gmail.com)
# @date     2018-08
# @brief    
# @version  0.0.1
# 
# Last Modified:  2018-08-30
# Modified By:    姜阳 (j824544269@gmail.com)
# 
################################################################################
set -e

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
CMAKE_SOURCE_DIR=$(pwd)
cd ${CMAKE_SOURCE_DIR}

if [ ! -d ./build ] 
then
   mkdir build 
fi

cd build && cmake ..  && make $1 -j8 && cd src 

./$1